- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      pacman: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/code.yml
    - include: tasks/docker.yml
    - include: tasks/node.yml