- hosts: localhost
  become: true
  connection: local
  pre_tasks:
    - name: update repositories
      pacman: update_cache=yes
      changed_when: False
  tasks:
    - include: tasks/update.yml
    - include: tasks/system.yml
    - include: tasks/code.yml
    - include: tasks/docker.yml
    - include: tasks/node.yml