---
- name: Install Visual studio code
  aur: name=visual-studio-code-bin
  become: false

- name: Install Jetbrains Toolbox
  aur: name=jetbrains-toolbox
  become: false

- name: Configure git name
  git_config:
    name: user.name
    scope: system
    value: Etienne Schmitz
- name: Configure git email
  git_config:
    name: user.email
    scope: system
    value: hello@etienne-schmitz.com

- name: Install python 2 (backwards compatible)
  pacman: 
    name: python2
    state: present

- name: Install termius
  aur: name=termius
  become: false 

- name: Install Deno
  aur: name=deno
  become: false

- name: Install Oh my Zsh
  aur: name=oh-my-zsh-git
  become: false

- name: Install Utils for dns
  pacman: 
    name: dnsutils
    state: present
