---
- name: Install Visual studio code
  pacman: 
    name: code
    state: present

- name: Install Jetbrains Toolbox
  aur: name=jetbrains-toolbox
  become: false

- name: Configure git name
  git_config:
    name: user.name
    scope: system
    value: Etienne Schmitz
- name: Configure git email
  git_config:
    name: user.email
    scope: system
    value: hello@etienne-schmitz.com
