---
- name: Install Visual studio code
  aur: name=visual-studio-code-bin
  become: false

- name: Install Jetbrains Toolbox
  aur: name=jetbrains-toolbox
  become: false

- name: Configure git name
  git_config:
    name: user.name
    scope: system
    value: Etienne Schmitz
- name: Configure git email
  git_config:
    name: user.email
    scope: system
    value: hello@etienne-schmitz.com

- name: Install python 2 (backwards compatible)
  pacman: 
    name: python2
    state: present

- name: Install termius
  aur: name=termius
  become: yes
  become_user: aur_builder

- name: Install Deno
  aur: name=deno
  become: yes
  become_user: aur_builder

- name: Install Oh my Zsh
  aur: name=oh-my-zsh-git
  become: yes
  become_user: aur_builder

- name: Install Utils for dns
  pacman: 
    name: dnsutils
    state: present

- name: Install java (openjdk)
  pacman:
      name:
        - jdk8-openjdk
        - jdk11-openjdk
        - jdk14-openjdk
      state: present

- name: Install gradle
  pacman:
    name: gradle
    state: present

- name: Install postman
  aur: name=postman-bin
  become: yes
  become_user: aur_builder

- name: Install filezilla
  pacman:
    name: filezilla
    state: present
