- name: Install node
  pacman:
    name: 
      - npm
      - nodejs
    state: present
- name: Install vue, angular, ionic
  npm:
    name: "@vue/cli @angular/cli @ionic/cli"
    global: yes
- name: Install npm-check-updates
  npm:
    name: npm-check-updates
    global: yes