- name: Install node
  pacman:
    name: 
      - npm
      - nodejs
      - yarn
    state: present
- name: Install vue
  npm:
    name: "@vue/cli"
    global: yes
- name: Install angular
  npm:
    name: "@angular/cli"
    global: yes
- name: Install ionic
  npm:
    name: "@ionic/cli"
    global: yes
- name: Install npm-check-updates
  npm:
    name: npm-check-updates
    global: yes
- name: Install moleculer
  npm:
    name: moleculer-cli
    global: yes