- name: Install discord
  pacman: 
    name: discord
    state: present

- name: Install Google chrome
  aur: name=google-chrome
  become: yes
  become_user: aur_builder

# - name: Install Spotify
#   aur: name=spotify
#   become: yes
#   become_user: aur_builder