- name: Install yet another yogurt (pacman for aur)
  pacman: 
    name: yay
    state: present

- name: Install discord
  pacman: 
    name: discord
    state: present

- name: Install Google chrome
  aur: name=google-chrome
  become: false

- name: Install Spotify
  aur: name=spotify
  become: false